replicaCount: 1

image:
  repository: ransperber/octoapp2
  tag: 3ac6abf
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

mongodb:
  image: mongo:6.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  storage:
    size: 1Gi
    class: gp2
    mode: Filesystem

service:
  mongodb:
    port: 27017

config:
  mongodb:
    service: mongodb-service
    port: "27017"
    database: inventory

ingress:
  appDomain: app.bokertovmatoki.online
  class: nginx
  port: 3000